[package]
name = "AOC2024"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
fxhash = "0.2.1"
indoc = "2.0.5"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"
ureq = "2.11.0"
